# Generated by Django 4.0.4 on 2022-06-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_resume_alter_appuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 14, 54, 36, 24743)),
        ),
    ]
